from rest_framework.views import exception_handler

from common.global_response import CommonResponse


def handle_exception(exc, context):
    response = exception_handler(exc, context)
    if response is not None:
        # Get the message from the exception, if available
        try:
            message = str(response.data.get("detail"))
            response = CommonResponse(
                data=None,
                message=message.replace('"', ""),
                res_status=response.status_code,
            )
        except Exception as e:
            response = CommonResponse(
                data=None,
                message=str(response.data[0]).replace('"', ""),
                res_status=response.status_code,
            )
    else:
        # In case no response is generated by DRF's default handler
        response = CommonResponse(
            data=None,
            res_status=500,
            message="서버 오류",
        )  # Use appropriate status

    return response
